# Contains a mapping of abrreviations and short names, to their respective major
# This is used by $major to aid with user input interpretation

major_abbrev = {
	"aaas": "African American and African Studies",
	"acty": "Accountancy",
	"advertising": "Advertising and Promotion",
	"ae": "Aerospace Engineering",
	"african studies": "African American and African Studies",
	"anth": "Anthropology",
	"aviation management": "Aviation Management and Operations",
	"business marketing": "Sales and Business Marketing",
	"business strategy": "Leadership and Business Strategy",
	"cheg": "Chemical Engineering",
	"chem": "Chemistry",
	"community development": "Youth and Community Development",
	"com": "Communication Studies",
	"consumer package goods marketing": "Food and Consumer Package Goods Marketing",
	"consumer sciences teacher education": "Family and Consumer Sciences Teacher Education",
	"cs": "Computer Science",
	"cycs": "Cybersecurity",
	"cyis": "Cybersecurity",
	"danc": "Dance",
	"dietetics": "Nutrition and Dietetics",
	"digital marketing": "Digital Marketing and eCommerce",
	"digital media": "Digital Media and Journalism",
	"diversity": "Diversity and Inclusion",
	"econ": "Economics",
	"ed": "Education and Human Development",
	"english: literature": "English: Literature and Language",
	"english: rhetoric": "English: Rhetoric and Writing Studies",
	"entrepreneurial engineering": "Industrial and Entrepreneurial Engineering",
	"envs": "Environmental and Sustainability Studies",
	"family developoment": "Child and Family Development",
	"fashion design": "Fashion Design and Development",
	"fcs": "Family and Consumer Sciences Teacher Education",
	"fin": "Finance",
	"fren": "French",
	"freshwater science": "Freshwater Science and Sustainability",
	"gws": "Gender and Womens Studies",
	"geog": "Geography",
	"ger": "German",
	"gist": "Global and International Studies",
	"gps": "Graphic and Printing Science",
	"healthcare services": "Healthcare Services and Sciences",
	"health education teacher education: k-12": "Physical and Health Education Teacher Education: K-12",
	"hearing sciences": "Speech, Language and Hearing Sciences",
	"hist": "History",
	"hsv": "Healthcare Services and Sciences",
	"human development": "Education and Human Development",
	"iee": "Industrial and Entrepreneurial Engineering",
	"inclusion": "Diversity and Inclusion",
	"integrated design": "Integrated Design and Manufacturing",
	"international studies": "Global and International Studies",
	"jpns": "Japanese",
	"lat": "Latin",
	"learning mathematics": "Teaching and Learning Mathematics",
	"math": "Mathematics",
	"media": "Media and Technology",
	"mktg": "Marketing",
	"me": "Mechanical Engineering",
	"media studies": "Film, Video and Media Studies",
	"mus": "Music",
	"nonprofit administration": "Public and Nonprofit Administration",
	"nur": "Nursing",
	"nutrition": "Nutrition and Dietetics",
	"o t": "Occupational Therapy",
	"padm": "Public and Nonprofit Administration",
	"papr": "Paper Engineering",
	"phil": "Philosophy",
	"pegn": "Physical and Health Education Teacher Education: K-12",
	"phys": "Physics",
	"ph": "Public Health",
	"printing science": "Graphic and Printing Science",
	"psci": "Political Science",
	"rel": "Religion",
	"regional planning": "Community and Regional Planning",
	"slhs": "Speech, Language & Hearing Sciences",
	"soc": "Sociology",
	"span": "Spanish",
	"special education learning disabilities k-12": "Special Education Learning Disabilities K-12 and Elementary Education PK-3",
	"sped": "Special Education Learning Disabilities K-12 and Elementary Education PK-3",
	"stat": "Statistics",
	"strategic communication: diversity": "Strategic Communication: Diversity and Inclusion",
	"strategic communication: leadership": "Strategic Communication: Leadership and Teamwork",
	"strategic communication: media": "Strategic Communication: Media and Technology",
	"sustainability studies": "Environmental and Sustainability Studies",
	"swrk": "Social Work",
	"teamwork": "Leadership and Teamwork",
	"theatre: design": "Theatre: Design and Technical Production",
	"tourism": "Tourism and Travel",
	"travel": "Tourism and Travel",
	"univ": "University Curriculum (Exploratory Advising)",
	"mfed": "Workforce Education & Development",
	"womens studies": "Gender and Womens Studies",
	"workforce education": "Workforce Education and Development"
}
