major_abbrev = {
	"ACTY": "Accountancy",
	"AE": "Aerospace Engineering",
	"AAAS": "African American and African Studies",
	"ANTH": "Anthropology",
	"CHEG": "Chemical Engineering",
	"CHEM": "Chemistry",
	"COM": "Communication Studies",
	"CS": "Computer Science",
	"CYIS": "Cybersecurity",
	"CYCS": "Cybersecurity",
	"DANC": "Dance",
	"ECON": "Economics",
	"ED": "Education and Human Development",
	"ENVS": "Environmental and Sustainability Studies",
	"FCS": "Family and Consumer Sciences Teacher Education",
	"FIN": "Finance",
	"FREN": "French",
	"GWS": "Gender and Womens Studies",
	"GEOG": "Geography",
	"GER": "German",
	"GIST": "Global and International Studies",
	"GPS": "Graphic and Printing Science",
	"HSV": "Healthcare Services and Sciences",
	"HIST": "History",
	"IEE": "Industrial and Entrepreneurial Engineering",
	"JPNS": "Japanese",
	"LAT": "Latin",
	"MKTG": "Marketing",
	"MATH": "Mathematics",
	"ME": "Mechanical Engineering",
	"MUS": "Music",
	"NUR": "Nursing",
	"O T": "Occupational Therapy",
	"PAPR": "Paper Engineering",
	"PHIL": "Philosophy",
	"PEGN": "Physical and Health Education Teacher Education: K-12",
	"PHYS": "Physics",
	"PSCI": "Political Science",
	"PADM": "Public and Nonprofit Administration",
	"PH": "Public Health",
	"REL": "Religion",
	"SWRK": "Social Work",
	"SOC": "Sociology",
	"SPAN": "Spanish",
	"SPED": "Special Education Learning Disabilities K-12 and Elementary Education PK-3",
	"SLHS": "Speech, Language & Hearing Sciences",
	"STAT": "Statistics",
	"UNIV": "University Curriculum (Exploratory Advising)",
	"WFED": "Workforce Education & Development"
}
